"""Fix foreign key relationship between GameLog and PlayerInfo

Revision ID: 2bf032a05a8b
Revises: 7afadabfeb8f
Create Date: 2024-12-12 16:19:47.504435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf032a05a8b'
down_revision = '7afadabfeb8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playerName', sa.String(length=50), nullable=True))
        batch_op.drop_index('ix_game_log_longName')
        batch_op.create_index(batch_op.f('ix_game_log_playerName'), ['playerName'], unique=False)
        
        batch_op.drop_constraint('fk_game_log_playerID', type_='foreignkey')
        batch_op.create_foreign_key('fk_game_log_playerID', 'players', ['playerID'], ['id'])
        batch_op.drop_column('longName')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('playerName', sa.String(length=50), nullable=False))
        batch_op.alter_column('playerID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_players_longName')
        batch_op.create_index(batch_op.f('ix_players_playerName'), ['playerName'], unique=False)
        batch_op.drop_column('longName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longName', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_index(batch_op.f('ix_players_playerName'))
        batch_op.create_index('ix_players_longName', ['longName'], unique=False)
        batch_op.alter_column('playerID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('playerName')
        batch_op.drop_column('id')

    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longName', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_game_log_playerID', type_='foreignkey')
        batch_op.create_foreign_key(None, 'players', ['playerID'], ['playerID'])
        batch_op.drop_index(batch_op.f('ix_game_log_playerName'))
        batch_op.create_index('ix_game_log_longName', ['longName'], unique=False)
        batch_op.drop_column('playerName')

    # ### end Alembic commands ###
