"""Initial migration

Revision ID: 379598c16872
Revises: 
Create Date: 2024-11-19 12:05:36.104550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379598c16872'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('data',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.String(length=10000),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('date')

    # ### end Alembic commands ###
